export * from './home/home.component';
export * from './about-us/about-us.component'
export * from './contact-us/contact-us.component'
export * from './our-store/our-store.component'
export * from './privacy-cookies/privacy-cookies.component'
export * from './terms-conditions/terms-conditions.component'
export * from './delivery/delivery.component'
export * from './faqs/faqs.component'
export * from './returns/returns.component'